#!/usr/bin/perl
use strict;
use warnings;
use diagnostics;
use utf8;
use open ':encoding(UTF-8)';
binmode STDOUT, ':encoding(UTF-8)';

my $input_filename = $ARGV[0];
my $output_filename = $input_filename =~ s/\.sk/\.en/r;

#open(my $input, '<:encoding(UTF-8)', $input_filename)
open(my $input, '<', $input_filename)
  or die "Could not open file '$input_filename': for reading $!";

open(my $output, ">$output_filename")
  or die "Could not open file '$output_filename' for writing: $!";

while (<$input>) {
    print translate($_);
}

sub translate {

# demonstratives

    s/(^| )(ten|tá|to)(?= |$)/$1that/;
    s/(^| )(tí|tie)(?= |$)/$1those/;

    s/ a / and /;
    s/^tu /here /;

    s/((?<= )|(?<=^))ja /I /;
    s/((?<= )|(?<=^))ty /you /;
    s/^my /we /;
    s/^vy /y'all /;
    s/^on /he /;
    s/^ona /she /;
    s/^oni /they /;
    s/^ony /they /;
    s/ som(?= |$)/ am/;

    s/ (si|sú|sme|ste)(?= |$)/ are/;
    s/ je(?= |$)/ is/;
    s/ nie (am|is|are)(?=$| )/ $1 not/;

    s/ idete / are going /;

    s/ cez / via /;

    s/ po / /;
    s/ zo? / from /;

    s/ býva(?=$| )/ resides/;

#Verbs
# Class 1 verbs: chytať
    s/ býva[^ \n]+(?=$| )/ reside/;
    s/ nebýva(?=$| )/ does not reside/;
    s/ nebýva[^ \n]+(?=$| )/ do not reside/;
    s/ chodieva[^ \n]+(?=$| )/ walk/;
    s/ chodieva(?=$| )/ walks/;
    s/ kon(a|á)[^ \n]+(?=$| )/ act/;
    s/ koná(?=$| )/ acts/;
    s/ nekon(a|á)[^ \n]+(?=$| )/ do not act/;
    s/ nekoná(?=$| )/ does not act/;
# commented out lines matches mother incorrectly
#    s/ m(a|á)[^ \n]{1,4}(?=$| )/ have/;
#    s/ m(a|á)[^ \n]{1,4}(?=$| )/ have/;
    s/ má(?=$| )/ has/;
    s/ nem(a|á)[^ \n]+(?=$| )/ do not have/;
    s/ nemá(?=$| )/ does not have/;
    s/ pamätá(?=$| )/ remembers/;
    s/ pamät[^ \n]+(?=$| )/ remember/;
    s/ nepamätá(?=$| )/ does not remember/;
    s/ nepamät[^ \n]+(?=$| )/ do not remember/;
    s/ počúva(?=$| )/ listens/;
    s/ počúva((m|t)e|jú)(?=$| )/ listen/;
    s/ nepočúva(?=$| )/ does not listen/;
    s/ nepočúva((m|t)e|jú)(?=$| )/ do not listen/;
    s/ pozn(a|á)[^ \n]+(?=$| )/ know/;
    s/ pozná(?=$| )/ knows/;
    s/ nepozn(a|á)[^ \n]+(?=$| )/ know not/;
    s/ nepozná(?=$| )/ knows not/;
    s/ prichádza[^ \n]+(?=$| )/ arrive/;
    s/ prichádza(?=$| )/ arrives/;
    s/ neprichádza[^ \n]+(?=$| )/ do not arrive/;
    s/ neprichádza(?=$| )/ does not arrive/;
    s/ rozpráva[^ \n]+(?=$| )/ speak/;
    s/ rozpráva(?=$| )/ speaks/;
    s/ nerozpráva[^ \n]+(?=$| )/ do not speak/;
    s/ nerozpráva(?=$| )/ does not speak/;
    s/ spá(?=$| )/ sleeps/;
#    s/ nesp(a|á)[^ \n]+(?=$| )/ do not sleep/;
    s/ nespá(?=$| )/ does not sleep/;
    s/ spáva(?=$| )/ is sleeping/;
    s/ spáva(me|te|jú)(?=$| )/ are sleeping/;
    s/ nespáva(?=$| )/ is not sleeping/;
    s/ nespáva(te|jú|me)(?=$| )/ are not sleeping/;
    s/ spieva(?=$| )/ sings/;
    s/ spieva((t|m)e|jú)(?=$| )/ sing/;
    s/ nespieva(?=$| )/ does not sing/;
    s/ nespieva((t|m)e|jú)(?=$| )/ do not sing/;
    s/ stráca(?=$| )/ loses/;
    s/ stráca(t|m)e(?=$| )/ lose/;
    s/ strácajú/ lose/;
    s/ nestráca(?=$| )/ does not lose/;
    s/ nestráca(t|m)e(?=$| )/ do not lose/;
    s/ nestrácajú/ do not lose/;
    s/ vstáva[^ \n]+(?=$| )/ get up/;
    s/ vstáva(?=$| )/ gets up/;
    s/ nevstáva[^ \n]+(?=$| )/ do not get up/;
    s/ nevstáva(?=$| )/ does not get up/;
    s/ vychádza[^ \n]+(?=$| )/ go out/;
    s/ vychádza(?=$| )/ goes out/;
    s/ nevychádza[^ \n]+(?=$| )/ do not go out/;
    s/ nevychádza(?=$| )/ does not go out/;
    s/ začin(a|á)[^ \n]+(?=$| )/ begin/;
    s/ začiná(?=$| )/ begins/;
    s/ nezačin(a|á)[^ \n]+(?=$| )/ do not begin/;
    s/ nezačiná(?=$| )/ does not begin/;
    s/ žiada[^ \n]+(?=$| )/ ask/;
    s/ žiada(?=$| )/ asks/;
    s/ nežiada[^ \n]+(?=$| )/ do not ask/;
    s/ nežiada(?=$| )/ does not ask/;
    s/ znamen(a|á)[^ \n]+(?=$| )/ mean/;
    s/ znamená(?=$| )/ means/;
    s/ neznamen(a|á)[^ \n]+(?=$| )/ do not mean/;
    s/ neznamená(?=$| )/ does not mean/;

# Class 7 verbs: robiť, vidieť, kričať
    s/ číta[^ ]*(?=$| )/ reads/;
    s/ chod(ia|(í(t|m)e))(?=$| )/ walk/;
    s/ chodí(?=$| )/ walks/;
    s/ nechod(ia|(í(t|m)e))(?=$| )/ do not walk/;
    s/ nechodí(?=$| )/ does not walk/;
    s/ nechodieva[^ \n]+(?=$| )/ are not walking/;
    s/ nechodieva/ is not walking/;
    s/ hovor[^ ]*(?=$| )/ speaks/;
    s/ kričí(?=$| )/ shouts/;
    s/ krič(í(m|t)e|ia)(?=$| )/ shout/;
    s/ nekričí(?=$| )/ does not shout/;
    s/ nekrič(í(m|t)e|ia)(?=$| )/ do not shout/;
    s/ robí(?=$| )/ makes/;
    s/ (robia|robí(m|t)e)(?=$| )/ make/;
    s/ nerobí(?=$| )/ does not make/;
    s/ ne(robia|robí(m|t)e)(?=$| )/ do not make/;
    s/ sedí(m|t)e/ are sitting/;
    s/ sedia/ are sitting/;
    s/ sedí/ sits/;
    s/ nesedí(m|t)e/ are not sitting/;
    s/ nesedia/ are not sitting/;
    s/ nesedí/ does not sit/;
    s/ vidí(m|š|te)(?=$| )/ see/;
    s/ vid(ia|í(t|m)e)(?=$| )/ see/;
    s/ vidí(?=$| )/ sees/;
    s/ nevidí(m|te)(?=$| )/ do not see/;
    s/ nevid(ia|í(t|m)e)(?=$| )/ do not see/;
    s/ nevidí(?=$| )/ does not see/;

# irregular verbs
    s/ vie(?=$| )/ is familiar with/;
    s/ (vie(t|m)e|vedia)(?=$| )/ are familiar with/;
    s/ nevie(?=$| )/ is not familiar with/;
    s/ ne(vie(t|m)e|vedia)(?=$| )/ are not familiar with/;


# Nouns

# Following "dub"

    my @nouns_dub = (
        [  'breh'  ,  'a riverbank', 'riverbanks'  ],
        [  'dom'  ,  'a home', 'homes'  ],
        [  'dvor'  ,  'a yard', 'yards'  ],
        [  'hrad'  ,  'a castle', 'castles'  ],
        [  'kvet'  ,  'a flower', 'flowers'  ],
        [  'les'  ,  'a forest', 'forests'  ],
        [  'obraz'  ,  'a picture', 'pictures'  ],
        [  'obchod'  ,  'a shop', 'shops'  ],
        [  'plot'  ,  'a fence', 'fences'  ],
        [  'strom'  ,  'a tree', 'trees'  ],
        [  'prst'  ,  'a finger', 'fingers'  ],
        [  'večer'  ,  'an evening', 'evenings'  ],
        [  'voz'  ,  'a vehicle', 'vehicle'  ]
    );

    foreach my $noun (@nouns_dub) {
        my $sk = $noun->[0];
        my $sing = $noun->[1];
        my $plur = $noun->[2];
        eval ("s/(^| )$sk(|a|e|om|u)(?=\$| )/\$1$sing/");
        eval ("s/(^| )$sk(och|y)(?=\$| )/\$1$plur/");
    }

# Following žena

    my @nouns_žena = (
      [  'cena',   'a price',  'prices'  ],
      [  'dedina',   'a village',  'villages'  ],
      [  'hlava',   'a head',  'heads'  ],
      [  'kniha',   'a book',  'books'  ],
      [  'luka',   'a meadow',  'meadows'  ],
      [  'matka',   'a mother',  'mothers'  ],
      [  'minúta',   'a minute',  'minutes'  ],
      [  'noha',   'a foot',  'feet'  ],
      [  'otázka',   'a qeustion',  'questions'  ],
      [  'práca',   'a job',  'jobs'  ],
      [  'rieka',   'a river',  'rivers'  ],
      [  'stena',   'a wall',  'walls'  ],
      [  'rodina',   'a family',  'families'  ],
      [  'škola',   'a school',  'schools'  ],
      [  'stavba',   'a building',  'buildings'  ],
      [  'ruka',   'a hand',  'hands'  ],
      [  'trieda',   'a village',  'villages'  ],
      [  'záhrada',   'a garden',  'gardens'  ],
      [  'žena',   'a woman',  'women'  ],
      [  'zima',   'a winter',  'winters'  ]
    );

    foreach my $noun (@nouns_žena) {
        my $stem = $noun->[0] =~ s/a$//r;
        my $sing = $noun->[1];
        my $plur = $noun->[2];
        eval ("s/(^| )$stem(|a|e|u)(?=\$| )/\$1$sing/");
        eval ("s/(^| )$stem(ách|y)(?=\$| )/\$1$plur/");
    }

# uncategorized nouns:
    s/(^| )aut(o|e)(?=$| )/$1a car/;
    s/( |^)aut(á|ách)(?=$| )/$1cars/;
    s/chlap(ovi)?(?= |$)/the fellow/;
    s/chlap(i|och)(?= |$)/the fellows/;
    s/(^| )družstv(o|e)(?=$| )/$1the team/;
    s/(^| )družstvá(ch)?(?=$| )/$1the teams/;
# jar follows kosš: "jari" is both plural-nominative/accusative and singular-locative
    s/jar(?=$| )/springtime/;
    s/((vo?|pri) ([^ ]+ )?)jari(?=$| )/$1springtime/;
    s/jar(i|iach)(?=$| )/the springtimes/;
    s/(^| )jese(ň|ni)(?=$| )/$1autumn/;
    s/(^| )jesen(e|iach)(?=$| )/$1the autumns/;
    s/( |^)let(o|e)(?= |$)/$1the summer/;
    s/letá(ch)?(?= |$)/summers/;
    s/mest(o|e)(?=$| )/the town/;
    s/(^| )mestá(?=$| )/$1towns/;
    s/mestá(ch)?(?=$| )/the towns/;
    s/(^| )muž(|a|ovi)(?=$| )/$1a man/;
    s/(^| )muž(i|ov|och)(?=$| )/$1men/;
    s/ot(ec|covi)(?=$| )/father/;
    s/ot(eci|coch)(?=$| )/the fathers/;
    s/ pán(|a)($| )/ gentleman$2/;
    s/ pán(i|ov)($| )/ gentlemen$2/;
    s/priateľ(ovi)?(?=$| )/a friend/;
    s/priateľ(i|och)(?=$| )/friends/;
    s/(^| )stanic(a|u)(?=$| )/$1station/;
    s/(^| )stanice(?=$| )/$1stations/;
    s/(^| )ulic(a|u|i)(?=$| )/$1the street/;
    s/(^| )ulice(?=$| )/$1streets/;
    s/ulic(e|iach)(?=$| )/the streets/;
    s/(^| )vec(?=$| )/$1thing/;
    s/(^| )veci(?=$| )/$1things/;

# Place names

    s/Amerik.(?=$| )/America/;
    s/Anglick.(?=$| )/England/;
    s/Belgick.(?=$| )/Belgium/;
    s/Bielorusk.(?=$| )/Belarus/;
    s/Bosn.(?=$| )/Bosnia/;
    s/Veľk.[^\s]? Británi.(?=$| )/Great Britain/;
    s/Čiern.[^ ]? Hor.(?=$| )/Montenegro/;
    s/(?=^| )Belgick.(?=$| )/Belgium/;
    s/Česk.(?=$| )/Czechia/;
    s/Čiern. Hor.(?=$| )/Montenegro/;
    s/Čín(a|u|y)(?=$| )/China/;
    s/Estónsk.(?=$| )/Estonia/;
    s/Európ.(?=$| )/Europe/;
    s/Fínsk.(?=$| )/Finland/;
    s/Francúzsk.(?=$| )/France/;
    s/Gréck.(?=$| )/Greece/;
    s/Hercegovin.(?=$| )/Herzegovina/;
    s/Holandsk.(?=$| )/Holland/;
    s/Chorvátsk.(?=$| )/Croatia/;
    s/Írsk.(?=$| )/Ireland/;
    s/Japonsk.(?=$| )/Japan/;
    s/Kanad.(?=$| )/Canada/;
    s/Lichtenštajnsk.(?=$| )/Liechtenstein/;
    s/Litv.(?=$| )/Lithuania/;
    s/Lotyšsk.(?=$| )/Latvia/;
    s/Luxembursk.(?=$| )/Luxembourg/;
    s/Mexik.(?=$| )/Mexico/;
    s/Maďarsk.(?=$| )/Hungary/;
    s/Moldavsk.(?=$| )/Moldova/;
    s/Nemeck.(?=$| )/Germany/;
    s/Nórsk.(?=$| )/Norway/;
    s/Poľsk.(?=$| )/Poland/;
    s/Portugalsk.(?=$| )/Portugal/;
    s/Rakúsk[ao](?=$| )/Austria/;
    s/Rusko(?=$| )/Russia/;
    s/(from )Ruska(?=$| )/$1Russia/;
    s/Škótsk.(?=$| )/Scotland/;
    s/Slovensk.(?=$| )/Slovakia/;
    s/Slovinsk.(?=$| )/Slovenia/;
    s/Španielsk.(?=$| )/Spain/;
    s/Srbsk.(?=$| )/Serbia/;
    s/Švajčiarsk.(?=$| )/Switzerland/;
    s/Švédsk.(?=$| )/Sweden/;
    s/Taliansk.(?=$| )/Italy/;
    s/Tureck.(?=$| )/Turkey/;
    s/Ukrajin.(?=$| )/Ukraine/;
    s/Vatikán.?(?=$| )/the Vatican/;
    s/(^| )americk[^$ \n]+(?=$| )/$1american/;

# Adjectives

    my @adjectives = (
        [  'bohatý'  ,  'rich'  ],
        [  'chorý'  ,  'sick'  ],
        [  'dobrý'  ,  'good'  ],
        [  'hlavný'  ,  'main'  ],
        [  'iný'  ,  'different'  ],
        [  'jednoduchý'  ,  'simple'  ],
        [  'ktorý'  ,  'which'  ],
        [  'nejaký'  ,  'some'  ],
        [  'nízky'  ,  'low'  ],
        [  'nový'  ,  'new'  ],
        [  'pravý'  ,  'right'  ],
        [  'pekný'  ,  'nice'  ],
        [  'posledný'  ,  'last'  ],
        [  'starý'  ,  'old'  ],
        [  'široký'  ,  'wide'  ],
        [  'šťastný'  ,  'happy'  ],
        [  'taký'  ,  'such'  ],
        [  'ťažký'  ,  'difficult'  ],
        [  'veľký'  ,  'large'  ],
        [  'vysoký'  ,  'tall'  ],
        [  'známy'  ,  'well-known'  ]
    );

    foreach my $adjective (@adjectives) {
        my $s = $adjective->[0];
        $s = substr($s, 0, length($s) - 1); # remove last character
        my $r = $adjective->[1];
        my $endings;
        if ($s =~ m/[áí][kmz]+$/) { # rhythmic rule
           $endings = '(a|ej|e|eho|i|om|u|y|ych)';
        } else {
           $endings = '(á|ej|é|ého|í|om|ú|ý|ých)';
        }
        my $x = "s/ $s$endings( a| the|)(?=\$| )/\$2 $r/";
        eval ($x);
    }

# Place name adjectives

    s/ anglick[^$ \n]+(?=$| )/ english/;
    s/ belgick[^$ \n]+(?=$| )/ belgian/;
    s/ bielorusk[^$ \n]+(?=$| )/ belarusian/;
    s/ bosniansk[^$ \n]+(?=$| )/ bosnian/;
    s/ britsk[^$ \n]+(?=$| )/ british/;
    s/ česk[^$ \n]+(?=$| )/ czech/;
    s/ čiernohorsk[^$ \n]+(?=$| )/ montenegrin/;
    s/ čínsk[^$ \n]+(?=$| )/ chinese/;
    s/ estónsk[^$ \n]+(?=$| )/ estonian/;
    s/ fínsk[^$ \n]+(?=$| )/ finnish/;
    s/ francúzsk[^$ \n]+(?=$| )/ french/;
    s/ gréck[^$ \n]+(?=$| )/ greek/;
    s/ hercegovsk[^$ \n]+(?=$| )/ herzegovinian/;
    s/ holandsk[^$ \n]+(?=$| )/ dutch/;
    s/ chorvátsk[^$ \n]+(?=$| )/ croatian/;
    s/ írsk[^$ \n]+(?=$| )/ irish/;
    s/ japonsk[^$ \n]+(?=$| )/ japanese/;
    s/ kanadsk[^$ \n]+(?=$| )/ canadian/;
    s/ lichtenštajnsk[^$ \n]+(?=$| )/ liechtensteinish/;
    s/ litovsk[^$ \n]+(?=$| )/ lithuanian/;
    s/ lotyšsk[^$ \n]+(?=$| )/ latvian/;
    s/ luxembursk[^$ \n]+(?=$| )/ luxembourgish/;
    s/ macedónsk[^$ \n]+(?=$| )/ macedonian/;
    s/ maďarsk[^$ \n]+(?=$| )/ hungarian/;
    s/ mexick[^$ \n]+(?=$| )/ mexican/;
    s/ moldavsk[^$ \n]+(?=$| )/ moldavian/;
    s/ nemeck[^$ \n]+(?=$| )/ german/;
    s/ nórsk[^$ \n]+(?=$| )/ norwegian/;
    s/ poľsk[^$ \n]+(?=$| )/ polish/;
    s/ portugalsk[^$ \n]+(?=$| )/ portugese/;
    s/ rakúsk[^$ \n]+(?=$| )/ austrian/;
    s/ rusk[^$ \n]+(?=$| )/ russian/;
    s/ škótsk[^$ \n]+(?=$| )/ scottish/;
    s/ slovensk[^$ \n]+(?=$| )/ slovakian/;
    s/ slovinsk[^$ \n]+(?=$| )/ slovenian/;
    s/ španielsk[^$ \n]+(?=$| )/ spanish/;
    s/ srbsk[^$ \n]+(?=$| )/ serbian/;
    s/ švajčiarsk[^$ \n]+(?=$| )/ swiss/;
    s/ švédsk[^$ \n]+(?=$| )/ swedish/;
    s/ taliansk[^$ \n]+(?=$| )/ italian/;
    s/ tureck[^$ \n]+(?=$| )/ turkish/;
    s/ ukrajinsk[^$ \n]+(?=$| )/ ukranian/;
    s/ vatikánsk[^$ \n]+(?=$| )/ vatican/;
    s/ Angličan(?=$| )/ an Englishman/;

# Demonyms

    s/ Angličanka(?=$| )/ English/;
    s/ Angličani?(?=$| )/ Englishmen/;
    s/ Angličanky(?=$| )/ English/;
    s/ Američan(ka)?(?=$| )/ an American/;
    s/ Američan(i|ky)(?=$| )/ Americans/;
    s/ Belgičan(ka)?(?=$| )/ a Belgian/;
    s/ Belgičan(i|ky)(?=$| )/ Belgians/;
    s/ Bielorus(?=$| )/ a Belarusian/;
    s/ Bielorusi(?=$| )/ Belarusians/;
    s/ Bosnia(k|čka)(?=$| )/ a Bosnian/;
    s/ Bosnia(ki|čky)(?=$| )/ Bosnians/;
    s/ Brit(ka)?(?=$| )/ a brit/;
    s/ Brit(i|ky)(?=$| )/ brits/;
    s/ Če(ch|ška)(?=$| )/ a Czech/;
    s/ Če(chi|šky)(?=$| )/ Czechs/;
    s/ Čiernohor(ec|ka)(?=$| )/ a Montenegrin/;
    s/ Čiernohor(eci|ky)(?=$| )/ Montenegrins/;
    s/ Číňan(ka)?(?=$| )/ Chinese/;
    s/ Číňan(i|ky)(?=$| )/ Chinese/;
    s/ Estón(ec|ka)(?=$| )/ an Estonian/;
    s/ Estón(eci|ky)(?=$| )/ Estonians/;
    s/ Európanka(?=$| )/ a European/;
    s/ Európan(i|ky)(?=$| )/ Europeans/;
    s/ Fín(ka)?(?=$| )/ a Finn/;
    s/ Fín(i|ky)(?=$| )/ Finns/;
    s/ Francúz[^\n ]*(?=$| )/ French/;
    s/ Grék(yňa)?(?=$| )/ a Greek/;
    s/ Grék(i|yňe)(?=$| )/ Greeks/;
    s/ Hercegovin(ec|ka)(?=$| )/ a Herzegovinian/;
    s/ Hercegovin(eci|ky)(?=$| )/ Herzegovinians/;
    s/ Holanďan(ka)?(?=$| )/ Dutch/;
    s/ Holanďan(i|ky)(?=$| )/ Dutch/;
    s/ Chorvát(ka)?(?=$| )/ a Croat/;
    s/ Chorvát(i|ky)(?=$| )/ Croatians/;
    s/ Ír(?=$| )/ an Irishman/;
    s/ Írka(?=$| )/ an Irishwoman/;
    s/ Ír(i|ky)(?=$| )/ Irish/;
    s/ Japon(ec|ka)(?=$| )/ Japanese/;
    s/ Japon(eci|ky)(?=$| )/ Japanese/;
    s/ Kanaďan(ka)?(?=$| )/ a Canadian/;
    s/ Kanaďan(i|ky)(?=$| )/ Canadians/;
    s/ Lichtenštajnčan(ka)?(?=$| )/ a Liechtensteiner/;
    s/ Lichtenštajnčan(i|ky)(?=$| )/ Liechtensteiners/;
    s/ Litovčan(ka)?(?=$| )/ a Lithuanian/;
    s/ Litovčan(i|ky)(?=$| )/ Lithuanians/;
    s/ Lotyš(ka)?(?=$| )/ a Latvian/;
    s/ Lotyš(i|ky)(?=$| )/ Latvians/;
    s/ Luxemburčan(ka)(?=$| )/ a Luxembourger/;
    s/ Luxemburčan(i|k.)(?=$| )/ Luxembourgers/;
    s/ Macedón(ec|ka)(?=$| )/ a Macedonian/;
    s/ Macedón(eci|ky)(?=$| )/ Macedonians/;
    s/ Maďar(ka)?(?=$| )/ a Hungarian/;
    s/ Maďar(i|ky)(?=$| )/ Hungarians/;
    s/ Mexičan(ka)?(?=$| )/ a Mexican/;
    s/ Mexičan(i|ky)(?=$| )/ Mexicans/;
    s/ Moldavčan(ka)?(?=$| )/ a Moldavian/;
    s/ Moldavčan(i|ky)(?=$| )/ Moldavians/;
    s/ Nem(ec|ka)(?=$| )/ a German/;
    s/ Nem(ec|ky)(?=$| )/ a German/;
    s/ Nemeci(?=$| )/ Germans/;
    s/ Nór(ka)?(?=$| )/ a Norwegian/;
    s/ Nór(i|ky)(?=$| )/ Norwegians/;
    s/ (Poľka|Poliak)(?=$| )/ a Pole/;
    s/ (Poliaki|Poľky)(?=$| )/ Poles/;
    s/ Portugal(ec|ka)(?=$| )/ a Portugese/;
    s/ Portugal(eci|ky)(?=$| )/ Portugese/;
    s/ Rakúšan(ka)?(?=$| )/ an Austrian/;
    s/ Rakúšan[^ \n]*(?=$| )/ Austrians/;
    s/ Rus(ka)?(?=$| )/ a Russian/;
    s/ Rus(i|ky)(?=$| )/ Russians/;
    s/ Škót(ka)?(?=$| )/ a Scot/;
    s/ Škót(i|ky)(?=$| )/ Scots/;
    s/ Slov(ák|enka)(?=$| )/ a Slovak/;
    s/ (Slováki|Slovenky)(?=$| )/ Slovaks/;
    s/ Slovin(ec|ka)(?=$| )/ a Slovene/;
    s/ (Slovinky|Slovineci)(?=$| )/ Slovenians/;
    s/ Španiel(ka)?(?=$| )/ a Spaniard/;
    s/ Španiel(i|ky)(?=$| )/ Spaniards/;
    s/ Srb(ka)?(?=$| )/ a Serb/;
    s/ Srb(i|ky)(?=$| )/ Serbians/;
    s/ Švajčiar(ka)?(?=$| )/ Swiss/;
    s/ Švajčiar(i|ky)(?=$| )/ Swiss/;
    s/ Švéd(ka)?(?=$| )/ a Swede/;
    s/ Švéd(i|ky)(?=$| )/ Swedes/;
    s/ Talian(ka)?(?=$| )/ an Italian/;
    s/ Talian(i|ky)(?=$| )/ Italians/;
    s/ Ukrajin(ec|ka)(?=$| )/ a Ukranian/;
    s/ Ukrajin(eci|ky)(?=$| )/ Ukranians/;

# Possessive pronouns

    my $p_endings = "(a|e|ej|ho|i|om|ich|u)?";
    my @possessives = (
        [  'm[ôo]j$p_endings'  ,  'my'  ],
        [  'n[aá]š$p_endings'  ,  'our'  ],
        [  'tvoj$p_endings'  ,  'your'  ],
        [  'v[aá]š$p_endings'  ,  "y'all's"  ],
        [  'jeho'  ,  'his'  ],
        [  'jej'  ,  'her'  ],
        [  'ich'  ,  'their'  ]
    );

    foreach my $p (@possessives) {
        my $s = $p->[0];
        my $r = $p->[1];
        my $x = "s/(^| )$s( (a|the))?(?= )/\$1$r/";
        eval ($x);
    }

    s/(I.*) svoj(|e|ej|ich|ho|om|u) (a |the )?/$1 my /;
    s/(you.*) svoj(|e|ej|ich|ho|om|u) (a |the )?/$1 your /i;


# Prepositions
    s/ vo? / in /;
    s/ pri / near /;


# add article before singular adjectives, excluding "which" and "some"
#    s/ have (?!which)(?!some)(.+)(?<!s)(?<!men)(?<!feet)$/ have a $2$2/;
# Since "class" ends in 's' is is incorrectly identified as plural by the preceeding line
#    s/ have (?!which)(?!some)(.+)(class)$/ have a $1$2/;
    s/ a (?=(a|i|o))/ an /;

# this one causes problem with 'ona nie je' -> 'she is not' becomes "she is a not'
#    s/ is (?!some)(?!which)/ is a /;
    s/ a such / such a /;

    s/ going via (.+)(?<!s)(?<!men)$/ going via a $1/;

    s/.*which.*/$&?/;

    return $_;
}
