#!/bin/sh

file=$1

# Primitive "translation" from Slovak to English

perl -i -p -e 's/^ja /I /' $file
perl -i -p -e 's/^tu /here /' $file
perl -i -p -e 's/ sú / are /' $file
perl -i -p -e 's/ je / is /' $file
perl -i -p -e 's/ mám / have /' $file

perl -i -p -e 's/ muž(|a)($| )/ man$2/' $file
perl -i -p -e 's/ muž(i|ov)($| )/ men$2/' $file
perl -i -p -e 's/ pán($| )/ gentleman$1/' $file
perl -i -p -e 's/ pány($| )/ gentlemen$1/' $file

perl -i -p -e 's/ dom($| )/ home$1/' $file
perl -i -p -e 's/ domy($| )/ homes$1/' $file
perl -i -p -e 's/ plot($| )/ fence$1/' $file
perl -i -p -e 's/ ploty($| )/ fences$1/' $file
perl -i -p -e 's/ kvet($| )/ flower$1/' $file
perl -i -p -e 's/ kvety($| )/ flowers$1/' $file
perl -i -p -e 's/ večer($| )/ evening$1/' $file
perl -i -p -e 's/ večery($| )/ evenings$1/' $file
perl -i -p -e 's/ voz($| )/ vehicle$1/' $file
perl -i -p -e 's/ vozy($| )/ vehicles$1/' $file
perl -i -p -e 's/ obraz($| )/ picture$1/' $file
perl -i -p -e 's/ obrazy($| )/ pictures$1/' $file
perl -i -p -e 's/ obchod($| )/ shop$1/' $file
perl -i -p -e 's/ obchody($| )/ shops$1/' $file
perl -i -p -e 's/ les($| )/ forest$1/' $file
perl -i -p -e 's/ lesy($| )/ forests$1/' $file
perl -i -p -e 's/ strom($| )/ tree$1/' $file
perl -i -p -e 's/ stromy($| )/ trees$1/' $file
perl -i -p -e 's/ prst($| )/ finger$1/' $file
perl -i -p -e 's/ prsty($| )/ fingers$1/' $file
perl -i -p -e 's/ dvor($| )/ yard$1/' $file
perl -i -p -e 's/ dvory($| )/ yards$1/' $file

perl -i -p -e 's/ stavb(a|u)($| )/ building$2/' $file
perl -i -p -e 's/ stavby($| )/ buildings$1/' $file
perl -i -p -e 's/ ruk(a|u)($| )/ hand$2/' $file
perl -i -p -e 's/ ruky($| )/ hands$1/' $file
perl -i -p -e 's/ tried(a|u)($| )/ class$2/' $file
perl -i -p -e 's/ triedy($| )/ classes$1/' $file
perl -i -p -e 's/ záhrad(a|u)($| )/ garden$2/' $file
perl -i -p -e 's/ záhrady($| )/ gardens$1/' $file
perl -i -p -e 's/ škol(a|u)($| )/ school$2/' $file
perl -i -p -e 's/ školy($| )/ schools$1/' $file
perl -i -p -e 's/ knih(a|u)($| )/ book$2/' $file
perl -i -p -e 's/ knihy($| )/ books$1/' $file
perl -i -p -e 's/ cen(a|u)($| )/ price$2/' $file
perl -i -p -e 's/ ceny($| )/ prices$1/' $file
perl -i -p -e 's/ brehy($| )/ riverbanks$1/' $file
perl -i -p -e 's/ breh($| )/ riverbank$1/' $file
perl -i -p -e 's/ otázk(a|u)($| )/ question$2/' $file
perl -i -p -e 's/ otázky($| )/ questions$1/' $file
perl -i -p -e 's/ dedin(a|u)($| )/ village$2/' $file
perl -i -p -e 's/ dediny($| )/ villages$1/' $file
perl -i -p -e 's/ noh(a|u)($| )/ foot$2/' $file
perl -i -p -e 's/ nohy($| )/ feet$1/' $file
perl -i -p -e 's/ hlav(a|u)($| )/ head$2/' $file
perl -i -p -e 's/ hlavy($| )/ heads$1/' $file
perl -i -p -e 's/ minút(a|u)($| )/ minute$2/' $file
perl -i -p -e 's/ minúty($| )/ minutes$1/' $file
perl -i -p -e 's/ sten(a|u)($| )/ wall$2/' $file
perl -i -p -e 's/ steny($| )/ wallss$1/' $file
perl -i -p -e 's/ riek(a|u)($| )/ river$2/' $file
perl -i -p -e 's/ rieky($| )/ rivers$1/' $file
perl -i -p -e 's/ lúk(a|u)($| )/ meadow$2/' $file
perl -i -p -e 's/ lúky($| )/ meadowss$1/' $file

perl -i -p -e 's/ ulic(a|u)($| )/ street$2/' $file
perl -i -p -e 's/ ulice($| )/ streets$1/' $file
perl -i -p -e 's/ stanic(a|u)($| )/ station$2/' $file
perl -i -p -e 's/ stanice($| )/ stations$1/' $file

perl -i -p -e 's/ vec($| )/ thing$1/' $file
perl -i -p -e 's/ veci($| )/ things$1/' $file

perl -i -p -e 's/ auto($| )/ car$1/' $file
perl -i -p -e 's/ autá($| )/ cars$1/' $file
perl -i -p -e 's/ mesto($| )/ town$1/' $file
perl -i -p -e 's/ mestá($| )/ towns$1/' $file


perl -i -p -e 's/ hlavn[^$ ]+($| )/ main$1/' $file
perl -i -p -e 's/ ktor[^$ ]+($| )/ which$1/' $file
perl -i -p -e 's/ vysok[^$ ]+($| )/ tall$1/' $file
perl -i -p -e 's/ nov[^$ ]+($| )/ new$1/' $file
perl -i -p -e 's/ prav[^$ ]+($| )/ right$1/' $file
perl -i -p -e 's/ širok[^$ ]+($| )/ wide$1/' $file
perl -i -p -e 's/ nejak[^$ ]+($| )/ some$1/' $file
perl -i -p -e 's/ tak[^$ ]+($| )/ such$1/' $file
perl -i -p -e 's/ nízk[^$ ]+($| )/ low$1/' $file
perl -i -p -e 's/ jednoduch[^$ ]+($| )/ simple$1/' $file
perl -i -p -e 's/ dobr[^$ ]+($| )/ good$1/' $file
perl -i -p -e 's/ pekn[^$ ]+($| )/ fine$1/' $file
perl -i -p -e 's/ posledn[^$ ]+($| )/ last$1/' $file


perl -i -p -e 's/ have (?!which)(?!some)(.+)(?<!s)(?<!men)(?<!feet)$/ have a $1$2/' $file
perl -i -p -e 's/ is (?!some)(?!which)/ is a /' $file
perl -i -p -e 's/ a such / such a /' $file
perl -i -p -e 's/.*which.*/$&?/' $file
perl -i -p -e 's/ have (.+ class)/ have a $1/' $file
